apiVersion: v1
kind: Secret
metadata:
  name: teletrack-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  GATEWAY_SERVICE_KEY: {{ .Values.secrets.gatewayServiceKey | quote }}
  INCIDENT-SERVICE-API-KEY: {{ .Values.secrets.incidentServiceApiKey | quote }}
  MAIL_USERNAME: {{ .Values.secrets.mailUsername | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
