spring:
  profiles:
    active: git
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mahmoud-47/teletrack360-config
          default-label: main
          clone-on-start: true
          # I'm goona leave this guy public as the project is public
#          username: ${GIT_USERNAME}
#          password: ${GIT_TOKEN}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

server:
  port: 8888



management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    health:
      show-details: always
    metrics:
      tags:
        application: ${spring.application.name}
